services:
  db:
    container_name: ${TITLE}-db
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

  wordpress:
    container_name: ${TITLE}-wp
    depends_on:
      - db
    build: ./
    volumes:
      - ./dist:/var/www/html/wp-content/themes/${TITLE}
      - wp_data:/var/www/html
      - ./wp-install.sh:/tmp/wp-install.sh
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    env_file:
      - .env
    ports:
      - "${IP}:8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    networks:
      - backend

  phpmyadmin:
    container_name: ${TITLE}-phpmyadmin
    # 開発時のみ起動: `docker compose --profile debug up -d`
    profiles: ["debug"]
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - "${IP}:8000:80"
    networks:
      - backend

volumes:
  db_data:
  wp_data:

networks:
  backend:
    driver: bridge
